name: BuildPodcast
on:
  schedule:
    - cron: '0 12 * * *'  # every day at 9, not sure that timezone, will need to tweak it
  #this will let us manually run it from the github actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '11'
      - name: Build project
        run: | 
          cd zoocast
          ./gradlew assemble
      - name: Generate podcast
        run: java -jar zoocast/build/libs/zooCast-1.0-SNAPSHOT.jar
      - name: Publish podcast
        run: |
            TODAYS_DATE=$(date +%Y-%m-%d)
            echo "Remove olf podcast"
            rm -f docs/zoo.xml
            cp zoo.xml docs/zoo.xml
            rm -f zoo.xml
            git add .
            git commit -m "update zoo cast for $TODAYS_DATE"
            echo '---git push it ----'
            git push
            echo Pushed the chnages!
          
